SET search_path TO 'schuh';

DROP TABLE IF EXISTS schuh_file CASCADE;
DROP TABLE IF EXISTS abbildung CASCADE;
DROP TABLE IF EXISTS modell CASCADE;
DROP TABLE IF EXISTS schuh CASCADE;

DROP TYPE IF EXISTS schuhtyp;
